CREATE TABLE Lead_Management (
    Lead_ID VARCHAR(20) PRIMARY KEY,
    Lead_Name VARCHAR(100),
    Company_Name VARCHAR(150),
    Industry VARCHAR(100),
    Country VARCHAR(100),
    Region VARCHAR(100),
    Lead_Source VARCHAR(100),
    Campaign_Name VARCHAR(150),
    Job_Title VARCHAR(100),
    Company_Size VARCHAR(50),
    Annual_Revenue DECIMAL(15,2),
    Website_Visits INT,
    Email_Opens INT,
    Email_Clicks INT,
    Webinar_Attendance VARCHAR(10),
    Product_Demo_Requested VARCHAR(10),
    Sales_Calls_Completed INT,
    Lead_Score INT,
    Conversion_Probability DECIMAL(5,2),
    Lead_Status VARCHAR(50),
    Assigned_Sales_Representative VARCHAR(100),
    Opportunity_Created VARCHAR(10),
    Converted_Status VARCHAR(50),
    Expected_Revenue DECIMAL(15,2),
    Last_Activity_Date DATE
);